<!ENTITY % attributClass "class (ABKonfiguration|Anwendungsbaustein|Anwendungsprogramm|AOVerbindung|Aufgabe|AufOrgKombination|Bausteinschnittstelle|Bausteintyp|Benutzungsschnittstelle|Datenbanksystem|Datenbanksystem|Datensatztyp|DBKonfiguration|DBVerwaltungssystem|Dokumentensammlung|Dokumententyp|Doppelkante|Ereignistyp|ETNTKombination|Kante|KommBeziehung|Kommunikationsstandard|KonAnwendungsbaustein|Nachrichtentyp|Netzprotokoll|Netztyp|Objekttyp|Organisationseinheit|Organisationsplan|PhysischerDVBaustein|RechAnwendungsbaustein|Softwareprodukt|Standort|Subnetz|Textfeld|TextfeldFach|TextfeldLog|TextfeldPhy)">
<!ENTITY % attributHash "hash CDATA">
<!ENTITY % attributLayer "layer (0|1|2|3|4)">
<!ENTITY % attributName "name (description|direction|disksize|end|inventar|master_slave|name|os_type|processor|ramsize|serial|start|state)">
<!ENTITY % attributType "type (gif/base64)">
<!ENTITY % attributColor "name (bg_color|fg_color|border_color)">

<!ELEMENT modell_3lgm_2 (objects,szenario+,images)>

<!ELEMENT header (title,description,version,author?)>
<!ELEMENT objects (element*)>
<!ELEMENT images (bitmap*)>

<!ELEMENT title (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT element (field*)> 
<!ATTLIST element
	%attributClass; #REQUIRED
	%attributHash; #REQUIRED
	%attributLayer; #REQUIRED
>

<!ELEMENT field (#PCDATA)>
<!ATTLIST field %attributName; #REQUIRED>

<!ELEMENT szenario (description, mapping, layer+)>

<!ELEMENT mapping (layout+)>

<!ELEMENT layout (color*,form?,line_thickness?,line_style?,form?,font_family?,font_style?,font_size?,x?,y?,width?,height?,icon?)>
<!ATTLIST layout %attributClass; #IMPLIED>

<!ELEMENT layer (layout, container*)>
<!ATTLIST layer %attributLayer; #REQUIRED>

<!ELEMENT container (layout?)>
<!ATTLIST container %attributHash; #REQUIRED>

<!ELEMENT bitmap (#PCDATA)>
<!ATTLIST bitmap
	%attributType; #REQUIRED
	%attributHash; #REQUIRED
>

<!ELEMENT color (red, green, blue, alpha)>
<!ATTLIST color %attributColor; #REQUIRED>

<!ELEMENT red (#PCDATA)> 
<!ELEMENT green (#PCDATA)> 
<!ELEMENT blue (#PCDATA)>
<!ELEMENT alpha (#PCDATA)>

<!ELEMENT line_thickness (#PCDATA)>
<!ELEMENT line_style (#PCDATA)>
<!ELEMENT form (#PCDATA)>
<!ELEMENT font_family (#PCDATA)>
<!ELEMENT font_style (#PCDATA)>
<!ELEMENT font_size (#PCDATA)>
<!ELEMENT x (#PCDATA)> 
<!ELEMENT y (#PCDATA)> 
<!ELEMENT width (#PCDATA)> 
<!ELEMENT height (#PCDATA)>
<!ELEMENT icon (#PCDATA)>