DIALOG_TITLE					Save Image

FILE_FILTER_BMP					Windows Bitmaps (*.bmp)
FILE_FILTER_BMP_EXT				bmp
FILE_FILTER_JPG					JPEG Image Files (*.jpg, *.jpeg)
FILE_FILTER_JPG_EXT				jpg jpeg
FILE_FILTER_PNG					Portable Network Graphics Files (*.png)
FILE_FILTER_PNG_EXT				png
FILE_FILTER_TIFF				Tagged Image File Format (*.tif, *.tiff)
FILE_FILTER_TIFF_EXT			tif tiff

RADIO_BUTTON_ORIGINAL_SIZE		Current Resolution
RADIO_BUTTON_MAXIMUM_SIZE		Maximum Resolution

ERROR_MESSAGE					An error occours while saving the image.
ERROR_TITLE						Error

MESSAGE_OUT_OF_MEMORY			Attention: If the image is very large the system can run out of memory and the image will not be saved.
