DIALOG_TITLE					Save Image

FILE_FILTER_BMP					Windows Bitmaps (*.bmp)
FILE_FILTER_BMP_EXT				bmp
FILE_FILTER_JPG					JPEG Image Files (*.jpg, *.jpeg)
FILE_FILTER_JPG_EXT				jpg jpeg
FILE_FILTER_PNG					Portable Network Graphics Files (*.png)
FILE_FILTER_PNG_EXT				png
FILE_FILTER_TIFF				Tagged Image File Format (*.tif, *.tiff)
FILE_FILTER_TIFF_EXT			tif tiff
FILE_FILTER_SVG					Scalable Vector Graphics (*.svg)
FILE_FILTER_SVG_EXT				svg

RADIO_BUTTON_NORMAL_SIZE		Medium (Zoom 100)
RADIO_BUTTON_MEDIUM_SIZE		High (Zoom 200)
RADIO_BUTTON_HIGH_SIZE			Ultra High (Zoom 500)
RADIO_BUTTON_ORIGINAL_SIZE		Current
RADIO_BUTTON_MAXIMUM_SIZE		Maximum (Zoom 1000)

ERROR_MESSAGE					An error occours while saving the image.
ERROR_TITLE						Error

TITLE_RESOLUTION				Resolution
