package de.imise.util;

import java.util.Arrays;
import java.util.Collection;

public class TestData {

    public static final String[] names = {
            "Serverraum CLI 1",
            "SUN UltraSparc || Workstation",
            "Zentrales Server-Subnetz",
            "Mobile Geräte für Axon Siemens",
            "PDA",
            "Axon Siemens Packautomat",
            "Packautomat",
            "Drucker",
            "Drucker/Scanner",
            "Handscanner",
            "Laborcomputer Apotheke",
            "PC",
            "Fax",
            "Fax / Telefon",
            "PACS-DB-Cluster",
            "RAD IMS1",
            "Datenbankserver",
            "RAD IMS2",
            "RIS Applikationsserver",
            "RIS-DB-Cluster",
            "RIS-DB-Server1",
            "RIS-DB-Server2",
            "RIS-Gateway-Server",
            "SAP R/3-Applikationsserver-Cluster",
            "SAP Applikationsserver 1(Produktion)",
            "Bereich 1, Liebigstr. 27",
            "SAP Applikationsserver 2(Produktion)",
            "SAP R/3-DB-Server-Cluster",
            "SAP DB-Server 1(Produktion)",
            "SAP DB-Server 2",
            "SAP RAID(Produktion)",
            "PC",
            "Nürnberger Str. 57MKG Ambulanz Behandlungssaal",
            "MKGW156076",
            "Nürnberger Str. 57MKG Ambulanz ChefsbehandlungRaum: NU57/210",
            "MKGW156090",
            "Nürnberger Str.57MKG Ambulanz AnmeldungRaum: NU57/217",
            "Nürnberger Straße",
            "DatenbankserverSAP(Test)",
            "Raid - SystemSAP",
            "Raid - System MCC",
            "ServerCOPRA3",
            "Raid - SystemSAP (Test)",
            "ServerCOPRA5",
            "Applikations- u.File-server u. PDC MCC",
            "ApplikationsserverSAPTest",
            "NCH Arbeits-platzrechner(Arzt)",
            "ServerCOPRA1",
            "ServerCOPRA7",
            "Datenbankserver MCC",
            "ServerCOPRA6",
            "DatenbankserverSAP(Test)",
            "Backup Domain Controller  MCC",
            "Datenbankserver MCC",
            "ApplikationsserverSAP(Produktion)",
            "ServerCOPRA2",
            "Backup Domain Controller  MCC",
            "Controller",
            "ServerCOPRA4",
            "Raid - SystemSAP",
            "Applikations- u.File-server u. PDC MCC",
            "NCH Arbeits-platzrechner(Sekretariat)",
            "KarteikartenKinderchirurgie",
            "Kinderchirurgie, Keller",
            "Karteikarten",
            "PC 1 KonsZahn",
            "Konservierende Zahnheilkunde, Ambulanz",
            "MRZ",
            "PC KiZahn",
            "Kinderzahnheilkunde, Ambulanz",
            "PC 2 KonsZahn",
            "PC 1 ORT",
            "Orthopädie, EG",
            "PC 2 ORT",
            "FehlkartenOrthopädie",
            "Fehlkarten",
            "Lager INZJohannisallee 32, EG",
            "Gebäude-Nr. 4271, EG",
            "Archivlager",
            "Lager INZJohannisallee 32, Keller",
            "Gebäude-Nr. 4271, Keller",
            "Lager INZBadehaus: Verwaltung, Keller",
            "Gebäude-Nr. 4285, Keller",
            "Lager INZBadehaus: Physiotherapie, Keller",
            "Gebäude-Nr. 4284, Keller",
            "PC 1 INZ",
            "PC 2 INZ",
            "Ausleihschein-ordner",
            "Ordner",
            "Faxgerät INZ",
            "Faxgerät",
            "Kopierer INZ",
            "Kopierer",
            "Archivmit-arbeiter(in) INZ",
            "Person",
            "Lager KCHKeller",
            "Lager KCHZentralarchiv",
            "Zentralarchiv,Josehphinenstr. 7",
            "Archivmit-arbeiter(in) KCH",
            "Lager KonsZahnBrambacher Str., 1. OG",
            "Lager KonsZahnBrambacher Str., Ambulanz",
            "Brambacher Str., Ambulanz",
            "Ambulanz-personal KonsZahn",
            "Lager ORTOrthopädie, EG",
            "Archivmit-arbeiter(in) ORT",
            "Ambulanz-personal KiZahn",
            "Lager KiZahnAmbulanz",
            "Netzdose KonsZahn1",
            "LWL-Netzsteckdose",
            "Netzdose KiZahn",
            "Aktive Komponenten des Datenkommunikationsnetzes",
            "aktive Komponente eines Kommunikationsnetzes",
            "PC1 ZA",
            "Drucker/Scanner ZA",
            "Kopierer / Faxgerät ZA",
            "Kopierer/Faxgerät",
            "Archivmit-arbeiter(in) ZA",
            "Lager ZA",
            "PC2 ZA",
            "PC (Laptop)",
            "PC3 ZA",
            "Netzdose ZA",
            "LIS Server",
            "Stationsdrucker",
            "Drucker",
            "Stationsfax",
            "Lager KonsZahnNürnberger Str. 57, 3. OG",
            "Nürnberger Str. 57, 3. OG",
            "AusleihbuchKinderchirurgie",
            "Buch",
            "KomServ Data Gate",
            "Raid - System",
            "Switch Catalyst5000",
            "Power HubAL 5000",
            "Ambulanz-personal chirtranspl",
            "PC chirtranspl",
            "Lager chirtransplAmbulanz, 1. Etage",
            "Archivmit-arbeiter(in) Strahlen",
            "PC Strahlen",
            "Lager Strahlen",
            "Archivmit-arbeiter(in) Urologie",
            "PC Uroamb",
            "PC Urostat",
            "Lager Urostat1.Etage, Raum 196 Keller, Raum K17",
            "Lager UroambAmbulanz",
            "Netzdose Uroamb",
            "Drucker Uroamb",
            "Kopierer Urostat",
            "Archivmitarbeiter(in) DiagnRad",
            "PC2 DiagnRad",
            "PC1 DiagnRad",
            "Lager DiagnRad",
            "Archivmitarbeiter(in) Kinderklinik",
            "PC kinderstat",
            "PC1-PC20 kinderamb",
            "Fehlkartenkinderamb",
            "Ausleihbuchkinderstat",
            "Lager kinderstat",
            "Lager kinderamb",
            "Netzdose Kinderklinik",
            "Archivmitarbeiter(in) Chirurgie",
            "Kopierer Chirstat",
            "KarteikartenChirstat",
            "PC1 Chiramb",
            "PC2 Chiramb",
            "Lager Chirurgie",
            "Ausleihhefterurostat",
            "Archivmitarbeiter(in)Nuklearmedizin",
            "PC Nukl",
            "Lager NuklNuklearmedizin",
            "Netzdose Nuklearmedizin",
            "Archivmitarbeiter(in) Augenklinik",
            "PC3 Augen",
            "PC1 Augen",
            "PC2 Augen",
            "Lager Augen",
            "Archivmit-arbeiter(in) HNO",
            "AusleihbuchHNOstat",
            "PC HNOstat",
            "KarteiHNOstat",
            "PC3 HNOamb",
            "PC1 HNOamb",
            "PC2 HNOamb",
            "AusleihbuchHNOamb",
            "KarteiHNOamb",
            "Lager HNO",
            "Archivmit-arbeiter(in) Haut",
            "PC2 Hautamb",
            "PC1 Hautamb",
            "PC1 Hautstat",
            "PC2 Hautstat",
            "Netzdose Haut",
            "AusleihlisteHautstat",
            "Lager Haut",
            "Archivmitarbeiter(in) Neurologie",
            "PC Neurostat",
            "Netzdose Neurostat",
            "AusleihbuchNeurologie",
            "Lager Neuro",
            "KarteiNeuroamb",
            "Archivmit-arbeiter(in) MKG",
            "PC MKGstat",
            "Lager MKG",
            "PC1 MKGamb",
            "PC2 MKGamb",
            "AusleihbuchMKGamb",
            "ChefsekretariatNCH",
            "PC1 NCHstat",
            "PC3 NCHstat",
            "PC2 NCHstat",
            "AusleihbuchNCHstat",
            "PC1 NCHamb",
            "PC2 NCHamb",
            "Lager NCH",
            "Netzdose NCH",
            "Netzdose MKG",
            "Dokumentations-mitarbeiterinKAI",
            "PC KAIamb",
            "Lager KAI",
            "AusleihbuchKAIstat",
            "Power HubAL 5000",
            "Hub",
            "MKGW156087",
            "Liebigstr.10-14MKG-1Raum: LI10/C232",
            "MKGW156088",
            "Liebigstr.10-14MKG-1Raum: LI10/C231",
            "MKGW156089",
            "Liebigstr.10-14MKG-1Raum: LI10/B203",
            "MKGW156066",
            "Paul-List-Str. 9MKG Amb. NachsorgeRaum: LI10/B202",
            "Sekretärin",
            "Patientenkartei(Klinik)",
            "Telefon(Sekretariat)",
            "PC",
            "PC-Netz Dr. Schmoranzer",
            "Praxis Dr. Schmoranzer",
            "PC-Netz",
            "eHealthConnect Server (geplant)",
            "ISDN-Netz der Telekom",
            "TeleKom",
            "Kommunikationsnetzwerk",
            "mednet- Kommuniktionsrechner Dr. Schmoranzer (geplant)",
            "Kommunikationsnetz des UKL",
            "verschiedene Applikations- und Schnittstellenserver",
            "SAP DB` local disks",
            "SAP AS1",
            "SAP AS3",
            "SAP HRP",
            "SAP BWP",
            "SAP HRQ/E",
            "SAP BWQ/E",
            "BACKUP",
            "Firewall",
            "Webmail- Server",
            "XXX",
            "Mail server3",
            "Intranet- Server",
            "Faxserver SAP",
            "Faxserver",
            "VLAN- Server",
            "SMTP viruscan",
            "MUSE",
            "AMOR",
            "KONAS",
            "§301",
            "Exchange",
            "FSC S80",
            "WebSweeper",
            "ISA-Cluster",
            "MobiDik",
            "Polypoint PEP",
            "FileService",
            "ViewPoint",
            "SAP updsvr",
            "eGate-Prod",
            "XXX",
            "SAP DB",
            "SAP CISAP AS",
            "SAP QTSSAP DB\"",
            "Fileserver MW",
            "FSC S80",
            "IMS 2",
            "LZ-Archiv",
            "Monitoring/Adm",
            "RAD-AMASS(Server)",
            "DB-Server",
            "MagicWeb Cluster",
            "BEF 2",
            "RIS",
            "Sprachserver",
            "MFI-Gateway",
            "DC OKL",
            "Printserver",
            "Anae- COPRA",
            "COPRA",
            "Radiance",
            "Infinity-GW",
            "SMS / User",
            "MagicLink",
            "eGate-TST/HSB",
            "Befunde",
            "PDS",
            "IMS 1",
            "BEF 1",
            "SAP (DB)/AS",
            "SAP (CI)SAP AS",
            "SAP UKPSAP EDU",
            "FC-Switch",
            "FC-Switch",
            "SAP-PRD-mirrorSAP-CI-mirrorSAP-UKPSAP-EDU",
            "FC-Switch",
            "FC-Switch",
            "SAP-PRDSAP-QTSSAP-CISAP-DB\"FileserverSAP-BackupFileserver-Backup",
            "Overland NEO 4200",
            "SAP-HRPSAP-HRQSAP-BWPSAP-BWQ",
            "LIS Server",
            "Institut für Klinische Chemie",
            "ZentrallaborIntranet Server",
            "Switch Catalyst5000",
            "Switch Catalyst",
            "MKGW156111",
            "BettenhausMKG FotoRaum: PL07/007",
            "MKGW156113",
            "Nürnberger Str. 57MKG Ambulanz OberarztRaum: NU57/003",
            "MKGW156112",
            "BettenhausB1/GB5Raum: PL09/101",
            "MKGW1560102",
            "Nürnberger Str. 57IMISE",
            "MKGW156110",
            "Paul-List-Str.9MKG RhinometrieRaum: PL09/101",
            "MKGW156085",
            "Liebigstr. 10-14MKG-1Raum: LI10/B207",
            "MKGW156098",
            "Nürnberger Str. 57MKG Ambulanz SchwesternRaum: NU57/212",
            "MKGW156099",
            "Paul-List-Str.9B1/GB5Raum: PL09/103",
            "MKGW156086",
            "Liebigstr.10-14MKG-1Raum: LI10/C224",
            "MKGW156079",
            "Liebigstr. 10-14MKG OPRaum: LI10/A202",
            "MKGW156080",
            "MKGW156082",
            "Liebigstr. 10-14MKG-1Raum: LI10/B206",
            "MKGW156084",
            "Liebigstr. 10-14MKG-1Raum: LI10/C226",
            "MKGW156070",
            "Nürnberger Str. 57MKG Ambulanz AssistentenRaum: NU57/209",
            "MKGW156072",
            "Nürnberger Str.57MKG ChefsekretariatRaum: NU57/206",
            "MKGW156073",
            "Nürnberger Str.57MKG KlinikdirektorRaum: NU57/207",
            "MKGW156074",
            "Nürnberger Str.57MKG Ambulanz sekretariatRaum: NU57/219",
            "MKGW156075",
            "MKGW156077",
            "Paul-List-Str.7MKG SekretariatRaum: PL07/027",
            "MKGW156083",
            "Liebigstr. 10-14MKG-1Raum: LI10/B204",
            "MKGW156065",
            "Paul-List-Str. 9Abteilung: MKG OPRaum: LI10/A115",
            "MKGW156067",
            "Paul-List-Str.7MKG ArchivRaum: PL07/132",
            "MKGW156105",
            "Liebigstr.10-14MKG OPLI10/A118.1",
            "MKGW156104",
            "Liebigstr.10-14MKG OPRaum: LI10/A113",
            "MKGW156071",
            "Nürnberger Str. 57MKG AVRaum: NU57/204",
            "MKGW156107",
            "Liebigstr.10-14MKG OPRaum: LI10/A-114.1",
            "MKGW156103",
            "Liebigstr.10-14MKG OPRaum: LI10/A143",
            "MKGW156106",
            "Liebigstr.10-14MKG OPRaum: Li10/A121.1",
            "MKGW156078",
            "Liebigstr. 10-14MKG LogopädieRaum: Li10/B-115",
            "MKGW156033",
            "Liebigstr. 10-14 Abteilung: MKG OPRaum: LI10/A213",
            "MKGW156068",
            "Paul-List-Str.7ZMG RöntgenRaum: PL07/137",
            "MKGW156035",
            "Paul-List-Str.9Abteilung: MKG AssistentenRaum: PL07/141",
            "PflegepersonalMKG",
            "Pflegepersonal",
            "Ärzte MKG",
            "SchreibpersonalMKG",
            "Schreibpersonal",
            "Laser-drucker",
            "Nadel-drucker",
            "Tinten-strahler",
            "Laser-drucker",
            "MKGW156081",
            "Liebigstr. 10-14MKG-1Raum: LI10/B205",
            "Laser-drucker",
            "Laser-drucker",
            "Laser-drucker",
            "Laser-drucker",
            "Laser-drucker",
            "Laser-drucker",
            "Laser-drucker",
            "Laser-drucker",
            "Laser-drucker",
            "Laser-drucker",
            "MKGW156098",
            "Laser-drucker",
            "Laser-drucker",
            "Laser-drucker",
            "Laser-drucker",
            "Laser-drucker",
            "Nadel-drucker",
            "Cluster für Sono-IS",
            "Cluster",
            "Cluster für Patho-IS",
            "Institut für Pathologie",
            "Qualitätsmanagement",
            "Stephanstr. 9, Qualitätsmanagement",
            "Postfächer",
            "MitarbeiterIn Qualitätsmanagement",
            "Bote Hauspost",
            "Posteingangsstelle der Deutschen Post",
            "Deutsche Post Transport und Läger",
            "Deutsche Post (phys. Werkzeuge)",
            "Postfach Quant",
            "MitarbeiterIn QUANT",
            "Server QUANT",
            "MCC-Server-Park",
            "Aufnahmebuch NCH",
            "papierbasiertes Aufnahmebuch",
            "Verlegungs- und Entlassungsscheine(patientenbezogen)",
            "Netz",
            "Pflegepersonal",
            "\"Graue Mappe\"",
            "Krankenakte",
            "Aktenarchiv(stationärePatientenakte)",
            "PC für altes PVS",
            "Arzthelfer",
            "Rollwagen(temp.Aktenarchiv)",
            "Telefon(Schwester-nzimmer)",
            "\"GrünerAuffangbehälter\"",
            "Notizblock",
            "RedIT.PRZ",
            "Subnetz PRZ",
            "BRZ",
            "Subnetz BRZ",
            "SAN 1",
            "storage area network",
            "SAN 2",
            "FC 1",
            "FC 2",
            "RAID 1.1",
            "RAID 2.1",
            "RAID",
            "Tape 1",
            "Tape-Library",
            "Fernwartung perdata",
            "Server Schließanlage Fakultät",
            "Fileserver Fakultät",
            "VMWare ESX01",
            "CAFM-Testsystem",
            "Magic Web Ersatz",
            "Teleradiologie",
            "SAN Management Server",
            "SAP BW Produktiv",
            "SAP BW QTS",
            "Domänen-Controller",
            "Domänen-Controller",
            "Exchange Node A",
            "Exchange Node B",
            "Kodix Server",
            "Backup Server",
            "Server Bildmanagement",
            "Server Zentrale Dienste",
            "SMS Server RAID System",
            "SMS Server",
            "SMTP Gateway",
            "CAFM Cluster Node A",
            "CAFM Cluster Node B",
            "Server LAN Management",
            "Server",
            "Server Lotus Notes Bereich 5",
            "Server SRV Management",
            "SAP Bandlaufwerk Backup",
            "Bandlaufwerk",
            "SAP",
            "SAP",
            "SAP",
            "SAP",
            "SAP FI",
            "SAP MM",
            "SAP CO",
            "FC Switch 1 Fabric 1",
            "FC Switch 1 Fabric 2",
            "FC Switch 3 Fabric 1",
            "FC Switch 4 Fabric 2",
            "FC Switch 5 Fabric 1",
            "FC Switch 6 Fabric 2",
            "Storagesystem Clariion CX600",
            "Speichersystem",
            "Storagesystem Clariion CX500",
            "CAS Centera 1",
            "CAS Centera 2",
            "SAP",
            "SAP",
            "SRV CAS Archivierung",
            "Firewall Checkpoint",
            "BVS Augenklinik, SRV Strahlentherapie",
            "DigiDik Diktatserver",
            "Server NAV",
            "NDMP Proxy",
            "Server Spectrometrie",
            "SPSS / IKA / Leisys, BiB /SigmaPlot/Stat",
            "Viewpoint Server",
            "Citrix TS1",
            "Citrix TS2",
            "OWA ISA Reverse Proxy / IAS",
            "TFTP/Stat/Syslog",
            "SAP Update / DRG SRV",
            "SAPUpd -> ExchProxy ! IBO !",
            "Paragraph 301 SRV",
            "EKS (CUVOS DB)",
            "SAP AMOR APO / IfAP- Index",
            "SAP MUSE / JONAS APO SRV",
            "DC",
            "DC 250",
            "Printserver",
            "SAP PBS Contentlink SRV",
            "PEP Dienstplan",
            "Copra IST",
            "SAP Mobidik SRV B2",
            "SAP Fax SRV Beschaffung",
            "Vlan Manager",
            "SAP Ausfall Konas SRV",
            "SAP Doc Node A",
            "SAP Doc Node B",
            "Intranet SRV",
            "ISA A",
            "ISA B",
            "WEBSweeper A",
            "WEBSweeper B",
            "File SRV Node A",
            "File SRV Node B",
            "Fax Server OneBox",
            "DECT Server",
            "SAP Router OSS",
            "SAP BW QTS alt",
            "Radiometer BGA",
            "Radiometer BGA",
            "Siemens Monitoring",
            "Siemens Monitoring",
            "SAP Innovit KV",
            "Copra OP",
            "SAP HR Produktiv",
            "SAP HR Cold Standby",
            "SAP HRQ/E",
            "Exch. Storage FiberCAT S80 alt",
            "Viewpoint Storage FiberCAT S80",
            "Aktenarchiv SRV",
            "Server 3",
            "Z1 MKG",
            "CUVOS SRV",
            "INKAS ZBSR Server",
            "HelpDesk Server",
            "MCC",
            "MCC",
            "FTP SRV extern",
            "alter Diacos SRV",
            "PC Blut",
            "Intranet Dienste Zahnklinik / IIS",
            "EMC SAN Konsole",
            "Web SRV neu",
            "ImageAcess Test, Schulungs SRV",
            "Tumor Server",
            "Benzing Gleitzeitsystem",
            "Interflex Zeiterfassung / Logbuch",
            "CUVOS gateway zu SAP",
            "ESB",
            "EuroSDS Zentralsteri",
            "Projectserver",
            "Raumbuchserver",
            "Testserver Applikationen",
            "Testserver Applikationen",
            "Testserver Infrastruktur",
            "Testserver Infrastruktur",
            "IDS Appliance 1",
            "IDS Appliance 2",
            "Raritanswitches",
            "Netzwertk-Switch",
            "Netzwerkswiches",
            "Router",
            "Netzwerk-Router",
            "Backup BandRoboter",
            "Backup Single Instancing Gateway",
            "TK-Anlage",
            "TK-Anlage",
            "Mini Switch 1",
            "Mini Switch 2",
            "Mini Switch 3",
            "Mini Switch 4",
            "Mini Switch 5",
            "Mini Switch 6",
            "Mini Switch n1",
            "Mini Switch n2",
            "Mini Switch n3",
            "Layer 3/4 Switch 1",
            "Layer 3/4 Switch 2",
            "Switch",
            "Firewall",
            "Layer 3/4 Switch 3",
            "Layer 3/4 Switch 4",
            "aisle 1",
            "aisle 2",
            "Firewall",
            "RAID 2.1",
            "Backup Server",
            "Entropycoding appliance",
            "Serverswitch PRZ",
            "Serverswitch BRZ",
            "Rootbridge",
            "Backup-Rootbridge",
            "Switche in anderen Häusern",
            "Layer 2 Verteiler in die Häuser",
            "Switch",
            "Switch",
            "A2",
            "A3",
            "A1",
            "B1",
            "Sekretärin",
            "Arzt",
            "Arbeits-platzrechner(Arzt)",
            "Arbeitsplatzrechner (Schwester)",
            "\"Spritzenzettel\"",
            "Bettenbelegungsplan",
            "\"Nachtbefundzettel\"",
            "Aktenarchiv",
            "Patientenbestellbuch",
            "Patientenbelegetafel",
            "Hinz-Dokumentation",
            "Patientenpflege-dokumentation",
            "Arztdokumentation",
            "Telefon(Arzt)",
            "Patientenakte(Klinik)",
            "Arbeits-platzrechner(Sekretariat)",
            "LAN",
            "FSC RX300",
            "FSC RX300",
            "CITRIX-Farm",
            "Laptops",
            "Access Point",
            "Managed Switch",
            "Stations Switch",
            "CITRIX-Clients",
            "Tablet PCs",
            "SAP-Clients",
            "SAP-Server",
            "digitales Diktiergerät (Speech Mike)",
            "analoges Diktiergerät",
            "Befundarchiv Pathologie",
            "Ablagefächer Pathologie",
            "Spracherkennungsserver",
            "Befundserver",
            "Laufwerk W: der HNO",
            "PC HNO OPVorraum",
            "HNO Operationssaal-Vorraum",
            "Server",
            "Switch",
            "Virtueller Server MRZs160026",
            "Virtueller Server mrzs152212",
            "Cluster Remus",
            "virtuell: Server SRZ",
            "virtuell: Server PRZ",
            "Firewall-Server",
            "Stations-PC",
            "virtuell: VM xyz908745",
            "Server 1",
            "Server 2",
            "Server 2*",
            "RedIT.SRZ",
            "virtuell: VM-Server-Farm",
            "Gruppierung: VM xyz908746",
            "Physische Kommunikation",
            "PC bei niedergelassenem Arzt",
            "Internet/DFN",
            "Chipkartenleser ORT",
            "GTDS-Clients",
            "MRZS 151231",
            "MRZS 151225",
            "MRZS 151227",
            "CIRSmedical Server",
            "Schweiz",
            "RAD IMS3",
            "Rad PC (Befundung)",
            "Bandroboter",
            "RAD Archivierung(ADIC)",
            "RAD-PDIR(Server)",
            "RAD UPS(Server)",
            "RAD Magic Link(Server)",
            "Liebigstr. 20, Radiologie",
            "ESXhost1",
            "ESXhost2",
            "ESXhost3",
            "ESXhost4",
            "ESXhost5",
            "ESXhost6",
            "ESXhost7",
            "ESXhost8",
            "ESXclusterPRZ",
            "ESXclusterSRZ",
            "Data Domain PRZ",
            "Data Domain SRZ",
            "DPM Server",
            "Backupserver EMC Networker",
            "VCB Proxy",
            "CX3-80",
            "CX3-40",
            "Backupstorage Netz",
            "Produktiv Netz",
            "SUN Storage STK",
            "SUN Storage",
            "SUN Storage",
            "Automat LightCycler",
            "LAbor für Virologie",
            "Archimedes Archivserver",
            "Automat Vitek2",
            "Labor für Mikrobiologische Diagnostik",
            "Automat GradientCycler",
            "Automat LightCycler",
            "Automat BactAllert 3D",
            "Data WarehouseServer",
            "Netzlaufwerk W auf Server",
            "PC Virologie",
            "PC Hygiene4",
            "Stabsstelle KrankenhaushygieneBüro, Liebigstraße 20",
            "PC für Thermologger",
            "PC Hygiene5",
            "PC ChemieImager",
            "PC Hygiene2",
            "PC BactView für BactAllert",
            "PC Hygiene3",
            "PC Hygiene1",
            "PC Virologie",
            "PC Virologie",
            "Scanner für Archivierung der Anforderungsbögen",
            "Thermologger Auslesegerät",
            "Scanner für erfassung der Anforderungsbögen",
            "Photometer",
            "Zentralrechner Virologie",
            "Zentrallabor CLAB Server",
            "Server",
            "Barcode-Scanner",
            "KomServ-Hardware",
            "PC Pathologie",
            "Server DC Pathos",
            "Mappen-Regal",
            "Präparate-Regal (Makropräparate)",
            "Sektionsbuch-Regal",
            "Shandon Laser-MicroWriter",
            "TCP/IP",
            "VPN",
            "RAID5-Speicher",
            "Kurzzeitarchiv",
            "Backup System",
            "Befundungsserver Server",
            "Cluster 3",
            "Cluster 4",
            "Cluster 2",
            "Cluster 1",
            "Diktat Server",
            "Cherry-Tastatur",
            "Liebigstraße 21 - PRZ",
            "SAN",
            "Liebigstraße 27 c - SRZ",
            "Data Domain",
            "DeDup Appliance",
            "ESXCluster",
            "KAP-XC-FS",
            "KAP-XC-DB",
            "KAP-XC-CON",
            "KAP-PM5-DC",
            "KAP-XC-WF",
            "KAP-PM5-Broker",
            "KAP-XC-CIVIS",
            "KAP-XC-CIVIS-Test",
            "Krankenversicherungskarte",
            "Blackberry",
            "BlackberryEnterpriseServer (BES)",
            "Beatmungsgerät",
            "Gateway",
            "Klinischer Arbeitsplatzrechner",
            "medizinisches Gerät",
            "Virtueller Server",
            "Vitaldatenmonitor",
            "Bettmonitor",
            "Liebigstraße 20, Station F1-2",
            "Beatmungsgerät",
            "Bettarbeitsplatz",
            "Arztrechner",
            "Copra-Gateway",
            "Copra Applikationsserver",
            "Copra-Server",
            "Rechenzentrum",
            "Copra Datenbankserver",
            "Infusionspumpe",
            "Schwesternrechner",
            "INOVIT",
            "Physische Datenverarbeitungsbausteinkonfiguration 13",
            "Physische Datenverarbeitungsbausteinkonfiguration 14",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "Server",
            "Testsystem",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "Physische Datenverarbeitungsbausteinkonfiguration 18",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "Physische Datenverarbeitungsbausteinkonfiguration 16",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "- <Konfiguration> -",
            "Server",
            "Clients",
            "Clients",
            "Server",
            "Clients",
            "Clients",
            "Server",
            "Physische Datenverarbeitungsbausteinkonfiguration 8",
            "Physische Datenverarbeitungsbausteinkonfiguration 22",
            "Physische Datenverarbeitungsbausteinkonfiguration 21",
            "Physical data processing configuration 1",
            "Physical data processing configuration 2",
            "Physische Datenverarbeitungsbausteinkonfiguration 9",
            "Physische Datenverarbeitungsbausteinkonfiguration 10",
            "Physische Datenverarbeitungsbausteinkonfiguration 11",
            "Physische Datenverarbeitungsbausteinkonfiguration 51",
            "Physische Datenverarbeitungsbausteinkonfiguration 52",
            "Physische Datenverarbeitungsbausteinkonfiguration 56",
            "Physische Datenverarbeitungsbausteinkonfiguration 57",
            "Physische Datenverarbeitungsbausteinkonfiguration 17",
            "Physische Datenverarbeitungsbausteinkonfiguration 21",
            "Physische Datenverarbeitungsbausteinkonfiguration 1",
            "Physische Datenverarbeitungsbausteinkonfiguration 2",
            "Physische Datenverarbeitungsbausteinkonfiguration 3",
            "Physische Datenverarbeitungsbausteinkonfiguration 4",
            "Physische Datenverarbeitungsbausteinkonfiguration 5",
            "Physische Datenverarbeitungsbausteinkonfiguration 7",
            "Physische Datenverarbeitungsbausteinkonfiguration 12",
            "Physische Datenverarbeitungsbausteinkonfiguration 15",
            "Physische Datenverarbeitungsbausteinkonfiguration 19",
            "Physische Datenverarbeitungsbausteinkonfiguration 17",
            "Physische Datenverarbeitungsbausteinkonfiguration 21",
            "Physische Datenverarbeitungsbausteinkonfiguration 10",
            "Physische Datenverarbeitungsbausteinkonfiguration 11",
            "Physische Datenverarbeitungsbausteinkonfiguration 12",
            "Physische Datenverarbeitungsbausteinkonfiguration 13",
            "Physische Datenverarbeitungsbausteinkonfiguration 8",
            "Physische Datenverarbeitungsbausteinkonfiguration 9",
            "Physische Datenverarbeitungsbausteinkonfiguration 22",
            "Physische Datenverarbeitungsbausteinkonfiguration 14",
            "Physische Datenverarbeitungsbausteinkonfiguration 4",
            "Physische Datenverarbeitungsbausteinkonfiguration 5",
            "Physische Datenverarbeitungsbausteinkonfiguration 18",
            "Physische Datenverarbeitungsbausteinkonfiguration 2",
            "Physische Datenverarbeitungsbausteinkonfiguration 3",
            "Physische Datenverarbeitungsbausteinkonfiguration 1",
            "- <Konfiguration> -",
            "Physical data processing configuration 1",
            "Physische Datenverarbeitungsbausteinkonfiguration 5",
            "Physische Datenverarbeitungsbausteinkonfiguration 20",
            "Physische Datenverarbeitungsbausteinkonfiguration 23",
            "Physische Datenverarbeitungsbausteinkonfiguration 24",
            "Physische Datenverarbeitungsbausteinkonfiguration 25",
            "Physische Datenverarbeitungsbausteink