#####################################
# English resources for FileChooser #
#####################################
MESSAGE_OVERWRITE_1				File '
MESSAGE_OVERWRITE_2				' already exists. Overwrite?
MESSAGE_SAVE_ERROR				Save Error
MESSAGE_INVALID_CHARS			The filename contains invalid characters.
MESSAGE_CANT_WRITE				Can not write to file. Please ensure that you can write in this directory and the file is not used by another application.