TITLE							Choose image file...
LABEL_PREVIEW					Image Preview
BUTTON_OPEN						Open
FILE_FILTER_IMAGE				JPEG, GIF and PNG Image Files (*.jpg, *.jpeg, *.gif, *.png)
FILE_FILTER_IMAGE_EXT			jpg jpeg gif png
FILE_FILTER_GIF					Graphics Interchange File Format (*.gif)
FILE_FILTER_GIF_EXT				gif
FILE_FILTER_JPEG				JPEG Image Files (*.jpg, *.jpeg)
FILE_FILTER_JPEG_EXT			jpg jpeg
FILE_FILTER_PNG					Portable Network Graphics Files (*.png)
FILE_FILTER_PNG_EXT				png
