################################################
# English resources for SelectMultiPathsDialog #
################################################

trans_subdir			Include Subdirectories
trans_dir_struct		Directory Tree
trans_dirs				Directories		
trans_close				Close
