########################
# Name des Metamodells #
########################
TLGMServiceMetaModel				Service-oriented with IHE
TLGMServiceMetaModel_description	This model type enables modelling of communication between application systems via services.<br><br>Additionally it contains an extension to model IHE concepts.


#################################################
# Knoten alphabetisch nach Klassenname sortiert #
#################################################
ApplicationComponent				Application component
ApplicationComponent_p				Application components
ApplicationSystem					Application system
ApplicationSystem_p					Application systems
CommunicationInterface				Communication interface
CommunicationInterface_p			Communication interfaces
DeviceClass							Device class
DeviceClass_p						Device classes
Function							Function
Function_p							Functions
InvokingInterface					Interface (invoking)
InvokingInterface_p					Interfaces (invoking)
Location							Location
Location_p							Locations
ObjectType							Object type
ObjectType_p						Object types
OrganisationalUnit					Organisational unit
OrganisationalUnit_p				Organisational units
OrganisationSystem					Organisation system
OrganisationSystem_p				Organisation systems
PhysicalDataProcessingComponent		Physical data processing component
PhysicalDataProcessingComponent_p	Physical data processing components
Process								Process
Process_p							Processes
ProvidingInterface					Interface (providing)
ProvidingInterface_p				Interfaces (providing)
Service								Service
Service_p							Services
ServiceClass						Service class
ServiceClass_p						Service classes
SoftwareProduct						Software product
SoftwareProduct_p					Software products
SystemOfConcepts					System of concepts
SystemOfConcepts_p					Systems of concepts
TransmissionMedium					Transmission medium
TransmissionMedium_p				Transmission mediums
Use									Usage
Use_p								Usages


#######################
# Assoziationsklassen #
#######################
CommunicationLink_Edge				Communication link
CommunicationLink_Edge_p			Communication links
DataTransmissionLink_Edge			Data transmission link
DataTransmissionLink_Edge_p			Data transmission links
StorageLink_Edge					Storage link
StorageLink_Edge_p					Storage links
SupportLink_Edge					Support link
SupportLink_Edge_p					Support links


#######################
# Kanten mit Richtung #
#######################
#ApplicationComponent_HasPartEdge_f								hat Teil
#ApplicationComponent_HasPartEdge_b								ist Teil von
#ApplicationComponent_CommunicationInterface_Edge_f				besitzt
#ApplicationComponent_CommunicationInterface_Edge_b				gehört zu
ApplicationComponent_CommunicationLink_Edge_f					is mediated by
ApplicationComponent_CommunicationLink_Edge_b					mediates
ApplicationComponent_PhysicalDataProcessingComponent_Edge_f								requires
ApplicationComponent_PhysicalDataProcessingComponent_Edge_b								is required from
ApplicationComponent_PhysicalDataProcessingComponent_RequiresForFunctionality_Edge_f	requires for functionality
ApplicationComponent_PhysicalDataProcessingComponent_RequiresForFunctionality_Edge_b	is required for functionality of
ApplicationComponent_PhysicalDataProcessingComponent_RequiresForStorge_Edge_f			requires for storage
ApplicationComponent_PhysicalDataProcessingComponent_RequiresForStorge_Edge_b			is required for storage of
ApplicationSystem_SoftwareProduct_Edge_f						bases on
ApplicationSystem_SoftwareProduct_Edge_b						is the basis of
CommunicationLink_Edge_f										transmits to
CommunicationLink_Edge_b										transmits from
DataTransmissionLink_Edge_f										transfers data to
DataTransmissionLink_Edge_b										receives data from
#DeviceClass_HasPartEdge_f										hat Teil
#DeviceClass_HasPartEdge_b										ist Teil von
#Function_HasPartEdge_f											hat Teil
#Function_HasPartEdge_b											ist Teil von
#Achtung: Assoziation mit doppelter Bedeutung -> 2 Richtungen
Function_ObjectType_Edge_f_f									processed
Function_ObjectType_Edge_f_b									interprets
Function_ObjectType_Edge_b_f									is interpreted by
Function_ObjectType_Edge_b_b									is processed by
Function_SoftwareProduct_Edge_f									can be supported by
Function_SoftwareProduct_Edge_b									can support
Function_Use_Edge_f												is done via
Function_Use_Edge_b												done
#Location_HasPartEdge_f											hat Teil
#Location_HasPartEdge_b											ist Teil von
#ObjectType_HasPartEdge_f										hat Teil
#ObjectType_HasPartEdge_b										ist Teil von
#OrganisationalUnit_HasPartEdge_f								hat Teil
#OrganisationalUnit_HasPartEdge_b								ist Teil von
OrganisationalUnit_Use_Edge_f									uses
OrganisationalUnit_Use_Edge_b									is used by
PhysicalDataProcessingComponent_DeviceClass_Edge_f				is of type
PhysicalDataProcessingComponent_DeviceClass_Edge_b				specified
#PhysicalDataProcessingComponent_HasPartEdge_f					hat Teil
#PhysicalDataProcessingComponent_HasPartEdge_b					ist Teil von
PhysicalDataProcessingComponent_Location_Edge_f					is located at
PhysicalDataProcessingComponent_Location_Edge_b					houses
PhysicalDataProcessingComponentVirtualises_Edge_f				virtualizes
PhysicalDataProcessingComponentVirtualises_Edge_b				is virtualized by
Process_Function_Edge_f											performs
Process_Function_Edge_b											is performed in
Service_CommunicationLink_Edge_f								is called via
Service_CommunicationLink_Edge_b								realizes call of
Service_Function_Edge_f											implements functionality for completing
Service_Function_Edge_b											is realized by the functionality of
Service_InvokingInterface_Edge_f								can be called from
Service_InvokingInterface_Edge_b								can call
#Achtung: Assoziation mit doppelter Bedeutung -> 2 Richtungen
Service_ObjectType_Edge_f_f										has as a result
Service_ObjectType_Edge_f_b										has parameter
Service_ObjectType_Edge_b_f										is parameter of
Service_ObjectType_Edge_b_b										is the result of
Service_ProvidingInterface_Edge_f								can be provided by
Service_ProvidingInterface_Edge_b								can provide
Service_ServiceClass_Edge_f										belongs to
Service_ServiceClass_Edge_b										contains
ServiceUses_Edge_f												is used by
ServiceUses_Edge_b												uses
StorageLink_Edge_f												stores
StorageLink_Edge_b												is stored by
SupportLink_Edge_f												supports
SupportLink_Edge_b												is supported by
TransmissionMedium_DataTransmissionLink_Edge_f					is transmitted via
TransmissionMedium_DataTransmissionLink_Edge_b					transmits


##############
# IHE Knoten #
##############
IheActorInstance					IHE Actor Instance
IheActorInstance_p					IHE Actor Instances
IheActor							IHE Actor
IheActor_p							IHE Actors
IheDomain							IHE Domain
IheDomain_p							IHE Domains
IheInterface						IHE Interface
IheInterface_p						IHE Interfaces
IheIntegrationProfile				IHE Integration Profile
IheIntegrationProfile_p				IHE Integration Profiles
IheInvokingInterface				IHE Interface (invoking)
IheInvokingInterface_p				IHE Interfaces (invoking)
IheProvidingInterface				IHE Interface (providing)
IheProvidingInterface_p				IHE Interfaces (providing)
IheTransaction						IHE Transaction
IheTransaction_p					IHE Transactions


###########################
# IHE-Assoziationsklassen #
###########################
IheCommunicationLink_Edge			IHE Communication link
IheCommunicationLink_Edge_p			IHE Communication links


##############
# IHE Kanten #
##############
IheIntegrationProfile_IheDomain_Edge_f					is published in
IheIntegrationProfile_IheDomain_Edge_b					publishes
IheIntegrationProfile_IheActor_Edge_f					contains
IheIntegrationProfile_IheActor_Edge_b					belongs to
ApplicationSystem_IheActorInstance_Edge_f				implements
ApplicationSystem_IheActorInstance_Edge_b				is implemented in
IheActor_IheActorInstance_Edge_f						is realized by
IheActor_IheActorInstance_Edge_b						acts as
IheActor_IheInterface_Edge_f							has
IheActor_IheInterface_Edge_b							belongs to
IheInterface_IheTransaction_Edge_f						invokes ( <- ) / provides ( -> ) 
IheInterface_IheTransaction_Edge_b						is invoked by ( -> ) / is provided by ( <- )
IheInvokingInterface_IheTransaction_Edge_f				invokes ( <- )
IheInvokingInterface_IheTransaction_Edge_b				is invoked by ( -> )
IheProvidingInterface_IheTransaction_Edge_f				provides ( -> )
IheProvidingInterface_IheTransaction_Edge_b				is provided by ( <- )
IheInterface_CommunicationInterface_Edge_f				is realized by
IheInterface_CommunicationInterface_Edge_b				acts as
#IheInvokingInterface_InvokingInterface_Edge_f			is realized by
#IheInvokingInterface_InvokingInterface_Edge_b			acts as
#IheProvidingInterface_ProvidingInterface_Edge_f			is realized by
#IheProvidingInterface_ProvidingInterface_Edge_b			acts as
IheCommunicationLink_Edge_f								transmits to
IheCommunicationLink_Edge_b								transmits from


#########
# Pfade #
#########
PATH_ApplicationSystem_IheActor_f	acts as
PATH_ApplicationSystem_IheActor_b	is realized by


###################
# Tabellen-Header #
###################
TABLE_NAME_OVERVIEW					Overview
HEADER_CONNECTION_TYPE				Connection Type
