########################
# Name des Metamodells #
########################
TLGMServiceMetaModel				Service-oriented with IHE
TLGMServiceMetaModel_description	This model type enables modelling of communication between application systems via services.<br><br>Additionally it contains an extension to model IHE concepts.


#################################################
# Knoten alphabetisch nach Klassenname sortiert #
#################################################
ApplicationComponent				Application component
ApplicationComponent_p				Application components
ApplicationSystem					Application system
ApplicationSystem_p					Application systems
CommunicationInterface				Communication interface
CommunicationInterface_p			Communication interfaces
DeviceClass							Device class
DeviceClass_p						Device classes
Function							Function
Function_p							Functions
InvokingInterface					Interface (invoking)
InvokingInterface_p					Interfaces (invoking)
Location							Location
Location_p							Locations
ObjectType							Object type
ObjectType_p						Object types
OrganisationalUnit					Organisational unit
OrganisationalUnit_p				Organisational units
OrganisationSystem					Organisation system
OrganisationSystem_p				Organisation systems
PartableApplicationComponent		Application component
PartableApplicationComponent_p		Application components
PhysicalDataProcessingComponent		Physical data processing component
PhysicalDataProcessingComponent_p	Physical data processing components
Process								Process
Process_p							Processes
ProvidingInterface					Interface (providing)
ProvidingInterface_p				Interfaces (providing)
Service								Service
Service_p							Services
ServiceClass						Service class
ServiceClass_p						Service classes
SoftwareProduct						Software product
SoftwareProduct_p					Software products
SystemOfConcepts					System of concepts
SystemOfConcepts_p					Systems of concepts
TransmissionMedium					Transmission medium
TransmissionMedium_p				Transmission mediums
Use									Usage
Use_p								Usages


########################################################################################################################################
# Edge class names  (= all association classes & edge classes, whose display name is needed in dialoges (only these and not all edges) #
########################################################################################################################################
ApplicationComponent_PhysicalDataProcessingComponent_RequiresForFunctionality_Edge		Functionality
ApplicationComponent_PhysicalDataProcessingComponent_RequiresForFunctionality_Edge_p	Functionalities
ApplicationComponent_PhysicalDataProcessingComponent_RequiresForStorage_Edge			Storage
ApplicationComponent_PhysicalDataProcessingComponent_RequiresForStorage_Edge_p			Storages
ApplicationSystem_SoftwareProduct_Edge				Installation	
ApplicationSystem_SoftwareProduct_Edge_p			Installations
CommunicationLink_Edge								Communication link
CommunicationLink_Edge_p							Communication links
DataTransmissionLink_Edge							Data transmission link
DataTransmissionLink_Edge_p							Data transmission links
PhysicalDataProcessingComponentVirtualises_Edge		Virtualisation
PhysicalDataProcessingComponentVirtualises_Edge_p	Virtualisations
StorageLink_Edge									Storage link
StorageLink_Edge_p									Storage links


#######################
# Kanten mit Richtung #
#######################
ApplicationComponent_PhysicalDataProcessingComponent_Edge_f								requires
ApplicationComponent_PhysicalDataProcessingComponent_Edge_b								is required from
ApplicationComponent_PhysicalDataProcessingComponent_RequiresForFunctionality_Edge_f	requires for functionality
ApplicationComponent_PhysicalDataProcessingComponent_RequiresForFunctionality_Edge_b	is required for functionality of
ApplicationComponent_PhysicalDataProcessingComponent_RequiresForStorage_Edge_f			requires for storage
ApplicationComponent_PhysicalDataProcessingComponent_RequiresForStorage_Edge_b			is required for storage of
ApplicationComponent_Use_Edge_f									supports
ApplicationComponent_Use_Edge_b									is supported by
ApplicationSystem_SoftwareProduct_Edge_f						bases on
ApplicationSystem_SoftwareProduct_Edge_b						is basis of
CommunicationLink_Edge_f										transmits to
CommunicationLink_Edge_b										transmits from
DataTransmissionLink_Edge_f										transfers data to
DataTransmissionLink_Edge_b										receives data from
#DeviceClass_HasPartEdge_f										hat Teil
#DeviceClass_HasPartEdge_b										ist Teil von
#Function_HasPartEdge_f											hat Teil
#Function_HasPartEdge_b											ist Teil von
#Achtung: Assoziation mit doppelter Bedeutung -> 2 Richtungen
Function_ObjectType_Edge_f_f									processed
Function_ObjectType_Edge_f_b									interprets
Function_ObjectType_Edge_b_f									is interpreted by
Function_ObjectType_Edge_b_b									is processed by
Function_SoftwareProduct_Edge_f									can be supported by
Function_SoftwareProduct_Edge_b									can support
Function_Use_Edge_f												is done via
Function_Use_Edge_b												done
#Location_HasPartEdge_f											hat Teil
#Location_HasPartEdge_b											ist Teil von
#ObjectType_HasPartEdge_f										hat Teil
#ObjectType_HasPartEdge_b										ist Teil von
#OrganisationalUnit_HasPartEdge_f								hat Teil
#OrganisationalUnit_HasPartEdge_b								ist Teil von
OrganisationalUnit_Use_Edge_f									uses
OrganisationalUnit_Use_Edge_b									is used by
#PartableApplicationComponent_HasPartEdge_f						hat Teil
#PartableApplicationComponent_HasPartEdge_b						ist Teil von
#PartableApplicationComponent_CommunicationInterface_Edge_f		besitzt
#PartableApplicationComponent_CommunicationInterface_Edge_b		gehört zu
PhysicalDataProcessingComponent_DeviceClass_Edge_f				is of type
PhysicalDataProcessingComponent_DeviceClass_Edge_b				specified
#PhysicalDataProcessingComponent_HasPartEdge_f					hat Teil
#PhysicalDataProcessingComponent_HasPartEdge_b					ist Teil von
PhysicalDataProcessingComponent_Location_Edge_f					is located at
PhysicalDataProcessingComponent_Location_Edge_b					houses
PhysicalDataProcessingComponentVirtualises_Edge_f				virtualizes
PhysicalDataProcessingComponentVirtualises_Edge_b				is virtualized by
Process_Function_Edge_f											performs
Process_Function_Edge_b											is performed in
Service_CommunicationLink_Edge_f								is called via
Service_CommunicationLink_Edge_b								realizes call of
Service_Function_Edge_f											implements functionality for completing
Service_Function_Edge_b											is realized by the functionality of
Service_InvokingInterface_Edge_f								can be called from
Service_InvokingInterface_Edge_b								can call
#Achtung: Assoziation mit doppelter Bedeutung -> 2 Richtungen
Service_ObjectType_Edge_f_f										has as a result
Service_ObjectType_Edge_f_b										has parameter
Service_ObjectType_Edge_b_f										is parameter of
Service_ObjectType_Edge_b_b										is the result of
Service_ProvidingInterface_Edge_f								can be provided by
Service_ProvidingInterface_Edge_b								can provide
Service_ServiceClass_Edge_f										belongs to
Service_ServiceClass_Edge_b										contains
ServiceUses_Edge_f												is used by
ServiceUses_Edge_b												uses
StorageLink_Edge_f												stores
StorageLink_Edge_b												is stored by
TransmissionMedium_DataTransmissionLink_Edge_f					is transmitted via
TransmissionMedium_DataTransmissionLink_Edge_b					transmits


##############
# IHE Knoten #
##############
IheActor							IHE Actor
IheActor_p							IHE Actors
IheActorInstance					IHE Actor Instance
IheActorInstance_p					IHE Actor Instances
IheActorInstanceInterface			IHE Interface
IheActorInstanceInterface_p			IHE Interfaces
IheActorInstanceInvokingInterface		IHE Interface (invoking)
IheActorInstanceInvokingInterface_p		IHE Interfaces (invoking)
IheActorInstanceProvidingInterface		IHE Interface (providing)
IheActorInstanceProvidingInterface_p	IHE Interfaces (providing)
IheDomain							IHE Domain
IheDomain_p							IHE Domains
IheInterface						IHE Actor Interface
IheInterface_p						IHE Actor Interfaces
IheIntegrationProfile				IHE Integration Profile
IheIntegrationProfile_p				IHE Integration Profiles
IheInvokingInterface				IHE Actor Interface (invoking)
IheInvokingInterface_p				IHE Actor Interfaces (invoking)
IheProvidingInterface				IHE Actor Interface (providing)
IheProvidingInterface_p				IHE Actor Interfaces (providing)
IheTransaction						IHE Transaction
IheTransaction_p					IHE Transactions


############################################################################################################################################
# IHE Edge class names  (= all association classes & edge classes, whose display name is needed in dialoges (only these and not all edges) #
############################################################################################################################################
IheActor_IheActor_MustBeGroupedWith_Edge	Grouping
IheActor_IheActor_MustBeGroupedWith_Edge_p	Groupings
IheActorInstanceCommunicationLink_Edge		IHE Communication link
IheActorInstanceCommunicationLink_Edge_p	IHE Communication links
IheActorInstance_SoftwareProduct_Edge		Installation	
IheActorInstance_SoftwareProduct_Edge_p		Installations
IheCommunicationLink_Edge					IHE Communication link
IheCommunicationLink_Edge_p					IHE Communication links


##############
# IHE Kanten #
##############
IheIntegrationProfile_IheDomain_Edge_f					is published in
IheIntegrationProfile_IheDomain_Edge_b					publishes
IheIntegrationProfile_IheActor_Edge_f					contains
IheIntegrationProfile_IheActor_Edge_b					belongs to
ApplicationSystem_IheActorInstance_Edge_f				implements
ApplicationSystem_IheActorInstance_Edge_b				is implemented in
IheActor_IheActorInstance_Edge_f						is realized by
IheActor_IheActorInstance_Edge_b						acts as
IheActor_IheActor_MustBeGroupedWith_Edge_f				must be grouped with
IheActor_IheActor_MustBeGroupedWith_Edge_b				grouping is required by 
IheActor_IheInterface_Edge_f							has
IheActor_IheInterface_Edge_b							belongs to
#IheActorInstance_IheActorInstanceInterface_Edge_f		owns
#IheActorInstance_IheActorInstanceInterface_Edge_b		belongs to
IheActorInstance_SoftwareProduct_Edge_f					bases on
IheActorInstance_SoftwareProduct_Edge_b					is basis of
IheInterface_IheTransaction_Edge_f						invokes ( <- ) / provides ( -> ) 
IheInterface_IheTransaction_Edge_b						is invoked by ( -> ) / is provided by ( <- )
IheInvokingInterface_IheTransaction_Edge_f				invokes ( <- )
IheInvokingInterface_IheTransaction_Edge_b				is invoked by ( -> )
IheProvidingInterface_IheTransaction_Edge_f				provides ( -> )
IheProvidingInterface_IheTransaction_Edge_b				is provided by ( <- )
#IheInterface_IheActorInstanceInterface_Edge_f			is realized by
#IheInterface_IheActorInstanceInterface_Edge_b			acts as
#IheInvokingInterface_IheActorInstanceInvokingInterface_Edge_f			is realized by
#IheInvokingInterface_IheActorInstanceInvokingInterface_Edge_b			acts as
#IheProvidingInterface_IheActorInstanceProvidingInterface_Edge_f			is realized by
#IheProvidingInterface_IheActorInstanceProvidingInterface_Edge_b			acts as
IheCommunicationLink_Edge_f								transmits to
IheCommunicationLink_Edge_b								transmits from
IheActorInstanceCommunicationLink_Edge_f				transmits to
IheActorInstanceCommunicationLink_Edge_b				transmits from
IheTransaction_IheCommunicationLink_Edge_f				is transmitted by
IheTransaction_IheCommunicationLink_Edge_b				transmits


#########
# Pfade #
#########
PATH_ApplicationSystem_IheActor_f	acts as
PATH_ApplicationSystem_IheActor_b	is realized by


###############################
# Consistency Error MetaPaths #
###############################
PATH_IheActorInstance_mustBeGroupedWith_IheActor					must be grouped with at least one more instance of
PATH_IheActorInstance_mustBeGroupedWith_IheActor_error_descrip		At least one more IHE Actor Instance must be applied to the Application System of this IHE Actor Instance.
PATH_IheActorInstance_mustBeGroupedWith_IheActor_error_descrip_long	At least one more of these IHE Actor Instances must be applied to the Application System of this IHE Actor Instance:	

PATH_ApplicationSystem_needsGroupingOf_IheActorInstances					needs at least one more instance of
PATH_ApplicationSystem_needsGroupingOf_IheActorInstances_error_descrip		At least one more IHE Actor Instance must be applied to the Application System.
PATH_ApplicationSystem_needsGroupingOf_IheActorInstances_error_descrip_long	At least one more of these IHE Actor Instances must be applied to the Application System:


###################
# Tabellen-Header #
###################
TABLE_NAME_OVERVIEW					Overview
HEADER_CONNECTION_TYPE				Connection Type
HEADER_ACCESS_TYPE					Access type
