package de.imise.tool3lgm.event;

import de.imise.tool3lgm.event.action.StaticAction;

/**
 * Identifiers für {@link StaticAction}
 * <p>
 * Über diese Identifier, können {@link StaticAction} ihre Attribute bekommen.
 */
public enum ActionIdentifier {

    // file
    ACTION_NEW_MODEL,
    ACTION_OPEN_MODEL,
    ACTION_SAVE_MODEL,
    ACTION_SAVE_MODEL_AS,
    ACTION_CLOSE_MODEL,
    ACTION_SHOW_MODEL_DESCRIPTION_FRAME,
    // import
    ACTION_IMPORT_SUBMODEL,
    ACTION_IMPORT_MODEL,
    ACTION_IMPORT_DATA,
    // export
    ACTION_EXPORT_GRAPHIC,
    ACTION_EXPORT_GRAPHML_YED,
    ACTION_EXPORT_GRAPHML_YFILES,
    ACTION_EXPORT_XSLT,
    ACTION_EXPORT_SUBMODEL,
    ACTION_EXPORT_HTML,
    ACTION_EXPORT_DATA,
    //exit
    ACTION_EXIT,

    // edit
    ACTION_UNDO,
    ACTION_REDO,
    ACTION_SEARCH,
    ACTION_SELECT_ALL,

    // view
    // toolbar
    ACTION_GRAPH_SHOW_SINGLE_LAYER_PERSPECTIVE,
    ACTION_GRAPH_SHOW_THREE_LAYER_PERSPECTIVE,
    ACTION_ACTIVATE_DOMAIN_LAYER,
    ACTION_ACTIVATE_LOGICAL_LAYER,
    ACTION_ACTIVATE_PHYSICAL_LAYER,
    ACTION_OPEN_GRAPH_VIEW_SETTINGS_DIALOG,
    ACTION_OPEN_MATRIX_VIEW,
    ACTION_GOTO_NEXT_VIEW,
    ACTION_GOTO_PREVIOUS_VIEW,

    // analysis
    ACTION_ANALYSIS_OPEN_REPOSITORY,
    ACTION_ANALYSIS_OPEN_EDITOR,
    ACTION_ANALYSIS_RESET_RESULT,
    ACTION_ANALYSIS_REDUNDANCY,
    OPTIONS_SIMPLE_REDUNDANCY_ANALYSIS,

    //context
    ACTION_SHOW_ELEMENTS_PROPERTY_DIALOG,

    // layout
    ACTION_OPEN_GLOBAL_LAYOUT_EDITOR,

    ACTION_ANALYSIS_CHOOSE_GRAPH_ANALYSIS_RESULT_COLOR,

    // extras
    ACTION_OPEN_USERFIELD_DEFINITION_DIALOG,
    ACTION_OPEN_USERFIELD_VALUE_EDITOR_DIALOG,

    // window
    ACTION_GRAPH_FRAMES_PARALLEL_ARRAGEMENT,
    ACTION_GRAPH_FRAMES_OVERLAPPING_ARRAGEMENT,

    // help
    ACTION_OPEN_HELP_DIALOG,
    ACTION_ACTIVATE_DIRECT_HELP,
    ACTION_SHOW_INFORMATION_SYSTEM_EVALUATION_TUTORIAL,
    ACTION_OPEN_URL_3LGM_WEBSITE,
    ACTION_OPEN_URL_ISSUE_TRACKER,
    ACTION_OPEN_URL_ONLINE_HELP,
    ACTION_OPEN_EXAMPLE_MODEL_FILE,
    ACTION_OPEN_FILE_CHOSSER_IN_MODEL_LIBRARY,
    ACTION_OPEN_ABOUT_DIALOG,
    ACTION_OPEN_CHOOSE_DEFAULT_METAMODEL_DIALOG,
    ACTION_IMPORT_LICENSE_FILE,

    ;

}
