#####################################
# English resources for FontChooser #
#####################################
font		Font
fonttype	Font Type
fontsize	Font Size
fontstyle	Font Style


normal	normal
bold	bold
italic	italic

preview	Preview