########################
# Name des Metamodells #
########################
TLGMOriginalMetaModel			Message Based (3LGM² Original)


# ###########################################
# Nodes, alphabetically sorted by Classname #
#############################################
ABKonfiguration					Application component configuration
ABKonfiguration_p				Application component configurations
Anwendungsbaustein				Application component
Anwendungsbaustein_p			Application components
Anwendungsprogramm				Application program
Anwendungsprogramm_p			Application programs
Aufgabe							Function
Aufgabe_p						Functions
AufOrgKombination				Function organisation unit combination
AufOrgKombination_p				Function organisation units combination
Bausteinschnittstelle			Component interface
Bausteinschnittstelle_p			Component interfaces
Bausteintyp						Component type
Bausteintyp_p					Component types
Benutzungsschnittstelle			User interface
Benutzungsschnittstelle_p		User interfaces
Client							Client
Client_p						Clients
Datenbanksystem					Database system
Datenbanksystem_p				Database systems
Datensatztyp					Dataset type
Datensatztyp_p					Dataset types
DBKonfiguration					Physical data processing configuration
DBKonfiguration_p				Physical data processing configurations
DBVerwaltungssystem				DB management system
DBVerwaltungssystem_p			DB management systems
Dokumentensammlung				Document collection
Dokumentensammlung_p			Document collections
Dokumententyp					Document type
Dokumententyp_p					Document types
EreignisDokumentenTyp			ETDT-Combination
EreignisDokumentenTyp_p			ETDT-Combinations
EreignisNachrichtenTyp			ETMT-Combination
EreignisNachrichtenTyp_p		ETMT-Combinations
Ereignistyp						Event type
Ereignistyp_p					Event types
EtntEtdtKombination				ETMT-ETDT-Combination
EtntEtdtKombination_p			ETMT-ETDT-Combinations
ExternalService					External Service
ExternalService_p				External Services
InternalService					Internal Service
InternalService_p				Internal Services
Kommunikationsprozess			Communication process
Kommunikationsprozess_p			Communication processes
Kommunikationsstandard			Communication standard
Kommunikationsstandard_p		Communication standards
KonAnwendungsbaustein			Paper-based appl. component
KonAnwendungsbaustein_p			Paper-based appl. components
Konfiguration					Configuration
Konfiguration_p					Configurations
LogischerSpeicher				Logical memory
LogischerSpeicher_p				Logical memories
Nachrichtentyp					Message type
Nachrichtentyp_p				Message types
Netzprotokoll					Net protocol
Netzprotokoll_p					Net protocols
Netztyp							Net type
Netztyp_p						Net types
Objekttyp						Entity type
Objekttyp_p						Entity types
Organisationseinheit			Organizational unit
Organisationseinheit_p			Organizational units
Organisationsplan				Working plan
Organisationsplan_p				Working plans
PhysischerDVBaustein			Physical data processing component
PhysischerDVBaustein_p			Physical data processing components
Prozess							Process
Prozess_p						Processes
RechAnwendungsbaustein			Computer-based appl. component
RechAnwendungsbaustein_p		Computer-based appl. components
Repraesentationsform			Representation form
Repraesentationsform_p			Representation forms
Schnittstelle					Interface
Schnittstelle_p					Interfaces
Softwareprodukt					Software product
Softwareprodukt_p				Software products
Standort						Location
Standort_p						Locations
Subnetz							Subnet
Subnetz_p						Subnets


#######################
# Association classes #
#######################
KommBeziehung					Communication link
KommBeziehung_p					Communication links


##############################
# Edgeclasses with direction #
##############################
AufAufOrgVerbindung_b			contains
AufAufOrgVerbindung_f			is contained in
AufAufVerbindung_b				is part of
AufAufVerbindung_f				has part

#Achtung: Assoziation mit doppelter Bedeutung -> 2 Richtungen
AufObjVerbindung_b_b			is updated by
AufObjVerbindung_b_f			is used by
AufObjVerbindung_f_b			uses
AufObjVerbindung_f_f			updates

AwbAwbkVerbindung_b				is contained in
AwbAwbkVerbindung_f				contains
AwbkAufOrgVerbindung_b			provides
AwbkAufOrgVerbindung_f			uses
AwbKommssVerbindung_b			belongs to
AwbKommssVerbindung_f			owns
AwpSwpVerbindung_b				is basis for
AwpSwpVerbindung_f				bases on

#Achtung: Assoziation mit doppelter Bedeutung -> 2 Richtungen
BssEtntVerbindung_b_b			can be sended by
BssEtntVerbindung_b_f			can be received by
BssEtntVerbindung_f_b			can receive
BssEtntVerbindung_f_f			can send

BssKommstVerbindung_b			is basis for
BssKommstVerbindung_f			bases on
DatenuebertragungsVerbindung_b	is connected with
DatenuebertragungsVerbindung_f	is connected with
DbsDatVerbindung_b				is stored by
DbsDatVerbindung_f				stores
DbsDbvsVerbindung_b				is controlling
DbsDbvsVerbindung_f				is controlled by
DoksDokVerbindung_b				is connected with
DoksDokVerbindung_f				stores
EtAufVerbindung_b				triggered
EtAufVerbindung_f				is triggered by an activity of
EtntDotVerbindung_b				is connected with
EtntDotVerbindung_f				is connected with
EtntEtVerbindung_b				is contained in
EtntEtVerbindung_f				contains
EtntKommstVerbindung_b			is connected with
EtntKommstVerbindung_f			belongs to
EtntNatVerbindung_b				is contained in 
EtntNatVerbindung_f				contains
KawbAwbVerbindung_b				is part of
KawbAwbVerbindung_f				has part
KawbDoksVerbindung_b			is connected with
KawbDoksVerbindung_f			is connected with
KawbOrgpVerbindung_b			is controlling
KawbOrgpVerbindung_f			is controlled by

#Achtung: Assoziation mit doppelter Bedeutung -> 2 Richtungen
KommbezEtntVerbindung_b_b		is sended by
KommbezEtntVerbindung_b_f		is received by
KommbezEtntVerbindung_f_b		receives
KommbezEtntVerbindung_f_f		sends

#Achtung: Assoziation mit doppelter Bedeutung -> 2 Richtungen mit jeweils gleicher 
#Bedeutung, weil die Endklassen der Kante gleich sind
KommBeziehung_b_b				receives from
KommBeziehung_b_f				sends to
KommBeziehung_f_b				receives from
KommBeziehung_f_f				sends to

ObjLogspVerbindung_b			is master of
ObjLogspVerbindung_f			has master
ObjObjVerbindung_b				is part of
ObjObjVerbindung_f				has part
ObjReprVerbindung_b				represents
ObjReprVerbindung_f				is represented by
OrgAufOrgVerbindung_b			is contained in
OrgAufOrgVerbindung_f			contains
OrgOrgVerbindung_b				is part of
OrgOrgVerbindung_f				has part
PdvbBtypVerbindung_b			is connected with
PdvbBtypVerbindung_f			is of
PdvbkAwbVerbindung_b			provides
PdvbkAwbVerbindung_f			can be used via
PdvbPdvbkVerbindung_b			contains
PdvbPdvbkVerbindung_f			is contained in
PdvbPdvbVerbindung_b			is part of
PdvbPdvbVerbindung_f			has part
PdvbStoVerbindung_b				houses
PdvbStoVerbindung_f				is located at
PdvbSubnVerbindung_b			is connected with
PdvbSubnVerbindung_f			belongs to
PdvbVirtualPdvbVerbindung_f		virtualises
PdvbVirtualPdvbVerbindung_b		is virtual at
PrzAufVerbindung_b				belongs to
PrzAufVerbindung_f				contains
RawbRawbVerbindung_b			is part of
RawbRawbVerbindung_f			has part
RawbAwpVerbindung_b				is controlling
RawbAwpVerbindung_f				is controlled by
RawbDbsVerbindung_b				belongs to
RawbDbsVerbindung_f				disposes of
SubnNetzpVerbindung_b			is basis for
SubnNetzpVerbindung_f			bases on 
SubnNetztVerbindung_b			is basis for
SubnNetztVerbindung_f			bases on 
SwpAufVerbindung_b				can be supported by
SwpAufVerbindung_f				can support

#neue Klassen für die Interne Leistungsverrechnung
ClientExternalServiceEdge_f				uses
ClientExternalServiceEdge_b				is used by
ExternalServiceInternalServiceEdge_f	uses
ExternalServiceInternalServiceEdge_b	is used by

# generated Names
in_oes						In org. unit


############
# Prozesse #
############
#++ Fehler 1 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
process_error_no_function		No process
process_error_no_function_1		The process does not contain tasks.
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

#++ Fehler 2 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
process_error_single_function	No process
process_error_single_function_1	A single enterprise function is not a (business) process.
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

#++ Fehler 3 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
process_error_no_process_step	No 3LGM²-buisness process step
process_error_no_process_step_1	"
##					Aufgabenname1
process_error_no_process_step_2	" at position [
##					Position
process_error_no_process_step_3	] is using no entity type updated by a previous enterprise function.
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


#########################
# ProzessStructurePanel #
#########################
PROCESS_PANEL_VERIFY	Verify
PROCESS_PANEL_ERROR		Error


####################
# KommProzessPanel #
####################
kein_OT					The end-function does not use an entity type that is updated by a preceding function.
keine_Start_Konf		The start-function has no configuration.
keine_Konfigs			Neither start-function nor end-function sind Teil einer Konfiguration.
keine_End_Konf			The end-function has no configuration.
konfigs_passen_nicht	No communication possible.
konfigs_teilw_gleich	Start configuration und end configuration are overlapping.


##############
# PathFinder #
##############
text_kommuniziert		is communicated by
PATH_is_executed_by_f	is executed by
PATH_is_executed_by_b	executes
PATH_is_supported_by_f	is supported by
PATH_is_supported_by_b	supports
PATH_is_executed_at_f	is executed at
PATH_is_executed_at_b	executes
PATH_is_stored_in_f		is stored in
PATH_is_stored_in_b		stores
PATH_is_installed_on_f	is installed on
PATH_is_installed_on_b	realises
PATH_is_used_by_f		is used by
PATH_is_used_by_b		uses
PATH_is_controlled_by_f	is controlled by
PATH_is_controlled_by_b	controlles
PATH_is_master_of_f		is master of
PATH_is_master_of_b		has master
