#Resources for the InterfaceCanSendOTAnalysis

NOT_SENDING_INTERFACE_DIALOG_TITLE Not a sending Interface
NOT_SENDING_INTERFACE_DIALOG_MESSAGE The selected interfaces doesn't send any object types.

CHOOSE_OBJECT_TYPE_DIALOG_TITLE Selection
CHOOSE_OBJECT_TYPE_DIALOG_MESSAGE Please select one or more elements: