package de.imise.util;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;

/**
 * This Class uses the version.info file, generated by the maven
 * git-commit-id-plugin, to set the version tag and the commit id tag for the
 * splashscreen
 *
 * @author AXS + Yoshi (05.11.2020)
 */
public class GitVersionInfoHandler {

    /**
     * Prefix with which the line in the version.info file begins, in which the
     * tag with the version and the commit ID is located. This prefix is used by
     * the {@link Properties} as a key to get the value with the version and the
     * commit.
     */
    private static final String VERSION_INFO_LINE_PREFIX_TAG_AND_COMMIT = "git.commit.id.describe";

    /**
     * Key string for the property with the branch name in the version-info
     * file.
     */
    private static final String VERSION_INFO_LINE_PREFIX_BRANCH = "git.branch";

    /**
     *
     */
    private static final String VERSION_INFO_COMMIT_COUNT_AFTER_LAST_TAG = "git.closest.tag.commit.count";

    /**
     *
     */
    private static final String VERSION_INFO_COMMIT_ID = "git.commit.id.abbrev";

    /** Git Version with tag and commit ID */
    public static class GitVersionInfo {

        /** The version */
        public String version = "Unknown Version";

        /** The commit ID */
        public String commit = "Unknown Commit";

        /** the branch name */
        public String branch = "Unknown Branch";

        /** number of commits after last tag */
        public int commitCount = -1;

        /**
         * If this string is contained in the version string, then the entire
         * version is considered to be a development version.
         */
        public String devVersionIndicator = null;

        @Override
        public String toString() {
            if (isReleaseBuild()) {
                return version;
            }
            return version + " (" + commit + (commitCount == -1 ? ")" : " + " + commitCount + ")");
        }

        /**
         * @return <code>true</code> if the {@link #devVersionIndicator} is
         *         contained in the version string
         */
        public boolean isDevelopmentBuild() {
            return devVersionIndicator != null && version.contains(devVersionIndicator);
        }

        /**
         * @return <code>true</code> if ith is not a development build
         * @see #isDevelopmentBuild()
         */
        public boolean isReleaseBuild() {
            return !isDevelopmentBuild();
        }

    }

    /**
     * Reads the git tag from the verion.info file and splits it into two
     * Strings, so that it fits the Splashscreen
     *
     * @param versionInfoFile
     * @param ignoreTagPrefix If the value with the tag and commit starts with
     *            this prefix, then the result will not contain this part of the
     *            string
     * @param devVersionIndicator If this string is contained in the version
     *            string, then the entire version is considered to be a deletion
     *            version.
     * @return {@link GitVersionInfo} object filled with the version data found
     *         in the file
     */
    public static final GitVersionInfo getGitVersionInfo(final File versionInfoFile, final String ignoreTagPrefix, final String devVersionIndicator) {
        GitVersionInfo versionInfo;
        try (FileInputStream fileInputStream = new FileInputStream(versionInfoFile)) {
            Properties properties = new Properties();
            properties.load(fileInputStream);
            //Version and Commit ID
            Object gitTag = properties.get(VERSION_INFO_LINE_PREFIX_TAG_AND_COMMIT);
            Object branchName = properties.get(VERSION_INFO_LINE_PREFIX_BRANCH);
            Object commitID = properties.get(VERSION_INFO_COMMIT_ID);
            Object commitCount = properties.get(VERSION_INFO_COMMIT_COUNT_AFTER_LAST_TAG);
            versionInfo = parseGitVersion(gitTag, branchName, commitID, commitCount, ignoreTagPrefix, devVersionIndicator);
        } catch (IOException e) {
            versionInfo = new GitVersionInfo();
        }
        return versionInfo;
    }

    /**
     * @param gitTag (String) object which has the form ignoreTahPrefix +
     *            realVersionString + devVersionIndicatorPostfix, e.g.
     *            "Tool3lgmVersion_" + "4.4.1" + "_dev". Some time the tag
     *            contains the postfix "-commitCount-commitID" e.g.
     *            "-306-g7038477".
     * @param branchName
     * @param commitID
     * @param commitCount
     * @param versionInfo
     * @param ignoreTagPrefix
     * @param devVersionIndicatorPostfix
     */
    public static GitVersionInfo parseGitVersion(final Object gitTag, final Object branchName, final Object commitID, final Object commitCount, final String ignoreTagPrefix, final String devVersionIndicatorPostfix) {
        GitVersionInfo versionInfo = new GitVersionInfo();
        versionInfo.devVersionIndicator = devVersionIndicatorPostfix;
        if (gitTag != null) {
            String gitTagString = gitTag.toString();
            int indexOfMinus = gitTagString.indexOf("-");
            if (indexOfMinus >= 0) {
                gitTagString = gitTagString.substring(0, indexOfMinus);
            }
            versionInfo.version = ignoreTagPrefix == null ? gitTagString : gitTagString.substring(ignoreTagPrefix.length());

            if (branchName != null) {
                versionInfo.branch = branchName.toString();
            }

            if (commitID != null) {
                versionInfo.commit = commitID.toString();
            }

            if (commitCount != null) {
                try {
                    String count = commitCount.toString();
                    versionInfo.commitCount = Integer.parseInt(count);
                } catch (Exception e) {
                    // ignore
                }
            }
        }
        return versionInfo;
    }

}
