package de.imise.util;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;

/**
 * This Class uses the version.info file, generated by the maven
 * git-commit-id-plugin, to set the version tag and the commit id tag for the
 * splashscreen
 *
 * @author AXS + Yoshi (05.11.2020)
 */
public class GitVersionInfoHandler {

    /**
     * Prefix with which the line in the version.info file begins, in which the
     * tag with the version and the commit ID is located. This prefix is used by
     * the {@link Properties} as a key to get the value with the version and the
     * commit.
     */
    private static final String VERSION_INFO_LINE_PREFIX_TAG_AND_COMMIT = "git.commit.id.describe";

    /**
     * Key string for the property with the branch name in the version-info
     * file.
     */
    private static final String VERSION_INFO_LINE_PREFIX_BRANCH = "git.branch";

    /** Git Version with tag and commit ID */
    public static class GitVersionInfo {

        /** The tag name */
        public String version = "Unknown Version";

        /** The commit ID */
        public String commit = "Unknown Commit";

        /** the branch name */
        public String branch = "Unknown Branch";

        /**
         * If this string is contained in the version string, then the entire
         * version is considered to be a development version.
         */
        public String devVersionIndicator = null;

        @Override
        public String toString() {
            if (isReleaseBuild()) {
                return version;
            }
            return version + " (" + commit + ")";
        }

        /**
         * @return <code>true</code> if the {@link #devVersionIndicator} is
         *         contained in the version string
         */
        public boolean isDevelopmentBuild() {
            return devVersionIndicator != null && version.contains(devVersionIndicator);
        }

        /**
         * @return <code>true</code> if ith is not a development build
         * @see #isDevelopmentBuild()
         */
        public boolean isReleaseBuild() {
            return !isDevelopmentBuild();
        }

    }

    /**
     * Reads the git tag from the verion.info file and splits it into two
     * Strings, so that it fits the Splashscreen
     *
     * @param versionInfoFile
     * @param ignoreTagPrefix If the value with the tag and commit starts with
     *            this prefix, then the result will not contain this part of the
     *            string
     * @param devVersionIndicator If this string is contained in the version
     *            string, then the entire version is considered to be a deletion
     *            version.
     * @return {@link GitVersionInfo} object filled with the version data found
     *         in the file
     */
    public static final GitVersionInfo getGitVersionInfo(final File versionInfoFile, final String ignoreTagPrefix, final String devVersionIndicator) {
        GitVersionInfo versionInfo = new GitVersionInfo();
        versionInfo.devVersionIndicator = devVersionIndicator;
        try (FileInputStream fileInputStream = new FileInputStream(versionInfoFile)) {
            Properties properties = new Properties();
            properties.load(fileInputStream);
            //Version and Commit ID
            Object gitTagObject = properties.get(VERSION_INFO_LINE_PREFIX_TAG_AND_COMMIT);
            if (gitTagObject != null) {
                String gitTag = gitTagObject.toString();
                int indexOfMinus = gitTag.indexOf("-");
                versionInfo.version = gitTag.substring(0, indexOfMinus);
                if (ignoreTagPrefix != null && versionInfo.version.startsWith(ignoreTagPrefix)) {
                    versionInfo.version = versionInfo.version.substring(ignoreTagPrefix.length());
                }
                versionInfo.commit = gitTag.substring(indexOfMinus + 1);
            }
            //Branch name
            Object branchName = properties.get(VERSION_INFO_LINE_PREFIX_BRANCH);
            if (branchName != null) {
                versionInfo.branch = branchName.toString();
            }

        } catch (IOException e) {
        }
        return versionInfo;
    }

}
