<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>de.imise</groupId>
	<artifactId>tool3lgm</artifactId>
 	<version>1.0</version>
	<packaging>jar</packaging>
	<dependencies>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.1.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest-all</artifactId>
			<version>1.3</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.jmockit</groupId>
			<artifactId>jmockit</artifactId>
			<version>1.18</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>
 		<dependency>
			<groupId>javax.help</groupId>
			<artifactId>javahelp</artifactId>
			<version>2.0.02</version>
		</dependency>
 		<dependency>
			<groupId>gnu-regexp</groupId>
			<artifactId>gnu-regexp</artifactId>
			<version>1.1.4</version>
		</dependency>
	 	<dependency>
			<groupId>net.sf.saxon</groupId>
			<artifactId>saxon</artifactId>
			<version>8.7</version>
		</dependency> 
  		<dependency>
			<groupId>de.axs</groupId>
			<artifactId>de-axs-utils</artifactId>
			<version>1.0.0</version>
			<!-- Das hier muss man machen, wenn man per Maven eine Datei lokal verlinken will. Hierbei liget die Datei im Projektordner unter Plugins/ -->
<!-- 			<scope>system</scope>
			<systemPath>${basedir}/../Plugins/de-axs-utils-1.0.0.jar</systemPath>
 -->			
 		</dependency>
<!--		<dependency>
			<groupId>de.imise</groupId>
			<artifactId>de.imise.twatd</artifactId>
			<version>0.0.1</version>
		</dependency>
 -->
 		<!-- https://mvnrepository.com/artifact/com.google.guava/guava -->
 		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>27.1-jre</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.apache.commons/commons-collections4 -->
		<dependency>
    		<groupId>org.apache.commons</groupId>
    		<artifactId>commons-collections4</artifactId>
    		<version>4.3</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.apache.commons/commons-lang3 -->
<!-- 		<dependency>
    		<groupId>org.apache.commons</groupId>
    		<artifactId>commons-lang3</artifactId>
    		<version>3.9</version>
		</dependency>
 -->		
	</dependencies>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
 	<build>
		<plugins>
			<plugin>
 				<artifactId>maven-resources-plugin</artifactId>
				<version>3.0.2</version>
				<executions>
					<execution>
						<id>copy-resources-tlgm_v3_0-action</id>
						<phase>validate</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<encoding>ISO-8859-1</encoding>
							<outputDirectory>${basedir}\target\classes\de\imise\tool3lgm\metamodel\tlgm_v3_0\action</outputDirectory>
							<resources>
								<resource>
									<directory>src\main\java\de\imise\tool3lgm\metamodel\tlgm_v3_0\action</directory>
									<filtering>true</filtering>
									<includes>
										<include>**/*.properties</include>
									</includes>
								</resource>
							</resources>
						</configuration>
					</execution>
					<execution>
						<id>copy-resources-tlgm_v3_0-analyse</id>
						<phase>validate</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<encoding>ISO-8859-1</encoding>
							<outputDirectory>${basedir}\target\classes\de\imise\tool3lgm\metamodel\tlgm_v3_0\analyse</outputDirectory>
							<resources>
								<resource>
									<directory>src\main\java\de\imise\tool3lgm\metamodel\tlgm_v3_0\analyse</directory>
									<filtering>true</filtering>
									<includes>
										<include>**/*.properties</include>
									</includes>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<!-- http://maven.apache.org/shared/maven-archiver/index.html -->
 			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<addClasspath>true</addClasspath>
							<mainClass>de.imise.tool3lgm.Tool3lgmMain</mainClass>
						</manifest>
						<manifestEntries>
							<SplashScreen-Image>splash.gif</SplashScreen-Image>
                        </manifestEntries>
					</archive>
				</configuration>
			</plugin>
		</plugins>
 		<resources>
			<resource>
				<directory>src\main\resources</directory>
			</resource>
		</resources>
		<testResources>
			<testResource>
				<directory>src\test\resources</directory>
			</testResource>
		</testResources>
 		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<configuration>
						<source>1.8</source>
						<target>1.8</target>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>