; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "3LGM² Tool"
#define MyAppVersion "4.3.0 (dev)"
#define MyAppPublisher "University Leipzig - IMISE"
#define MyAppURL "http://www.3lgm2.de"
#define MyAppExeName "3lgm2tool.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{88B62F13-55E9-4E6B-96B2-9F2D0217F0FB}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\3LGM2-Tool
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputDir=C:\Users\sippe\git\3LGM\tool-3lgm2\de.imise.tool3lgm.deploy\DeployResults
OutputBaseFilename=setup3lgm_V4.3.0_(dev)
SetupIconFile=C:\Users\sippe\git\3LGM\tool-3lgm2\de.imise.tool3lgm.deploy\DeployScriptsAndTools\Icons\toolIcon_gross.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "C:\Users\sippe\git\3LGM\tool-3lgm2\de.imise.tool3lgm.deploy\Tool3lgm\3lgm2tool.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\sippe\git\3LGM\tool-3lgm2\de.imise.tool3lgm.deploy\Tool3lgm\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Registry]
Root: "HKCR"; Subkey: ".3lgm"; ValueType: string; ValueData: "tool3lgm"; Flags: uninsdeletekey
Root: "HKCR"; Subkey: ".z3lgm"; ValueType: string; ValueData: "tool3lgm"; Flags: uninsdeletekey
Root: "HKCR"; Subkey: "tool3lgm"; ValueType: string; ValueData: "3LGM² Tool"; Flags: uninsdeletekey
Root: "HKCR"; Subkey: "tool3lgm\DefaultIcon"; ValueType: string; ValueData: "{app}\{#MyAppExeName},0"
Root: "HKCR"; Subkey: "tool3lgm\shell\open\command"; ValueType: string; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
