#######################
# Suche Ersetzen #
#######################
TOOLS_FINDREPLACEPANEL_FIND			Find
TOOLS_FINDREPLACEPANEL_REPLACE_ALL	Replace all
TOOLS_FINDREPLACEPANEL_R			Replace
TOOLS_FINDREPLACEPANEL_RF		Replace/Find
TOOLS_FINDREPLACEPANEL_TITLE 			Find and Replace
TOOLS_FINDREPLACEPANEL_CB_IC			Ignore case
TOOLS_FINDREPLACEPANEL_RB_F			Forward
TOOLS_FINDREPLACEPANEL_RB_B			Backward
TOOLS_FINDREPLACEPANEL_CB_RE		Regular expressions
TOOLS_FINDREPLACEPANEL_CB_WW		Whole word
TOOLS_FINDREPLACEPANEL_TT_WW		Find only whole words (surrounded by space)
TOOLS_FINDREPLACEPANEL_RB_SCOPE		in selection
TOOLS_FINDREPLACEPANEL_RB_NOSCOPE	All
TOOLS_FINDREPLACEPANEL_RBS_SCOPE	Scope
TOOLS_FINDREPLACEPANEL_RBS_DIR		Direction
TOOLS_FINDREPLACEPANEL_CBS_OPT		Options
TOOLS_FINDREPLACEPANEL_CB_WA		Wrap search
